use_frameworks!

target 'SwiftValidators_Example' do
  pod 'SwiftValidators', :path => '../'

  target 'SwiftValidators_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
